version: '3.8'

services:
  user-manager:
    image: nivaldeir/user-manager:v1
    restart: unless-stopped
    ports:
      - 3000:8080
    environment:
      WSRS_DATABASE_PORT: ${WSRS_DATABASE_PORT:-5432}
      WSRS_DATABASE_NAME: ${WSRS_DATABASE_NAME}
      WSRS_DATABASE_USER: ${WSRS_DATABASE_USER}
      WSRS_DATABASE_PASSWORD: ${WSRS_DATABASE_PASSWORD}
      WSRS_DATABASE_HOST: db
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CLIENT_URL_SUCCESS: "/"
      CLIENT_URL_ERROR: "/login"
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - public
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${WSRS_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${WSRS_DATABASE_USER}
      POSTGRES_PASSWORD: ${WSRS_DATABASE_PASSWORD}
      POSTGRES_DB: ${WSRS_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - public

volumes:
  db:

networks:
  public:
    driver: bridge
